### ISSUE TITLE
Morning Code Review with Stand-Up Team

### ISSUE THREAD

**Issue by akshay-narkar** [SarvarKh/Enumerables#1]
If you have any comments, please leave them below

**Comment by akshay-narkar** [comment]
1. Make use of .size instead of .length to cover ranges as well.
2. Get Rubocop working
3. Replace for loop

**Comment by apricot12** [comment]
1. Try to replace for loops.
2. Make sure rubocop is up and running and that you use inline configs for rubocop.

**Comment by Andrik27001** [comment]
- Try to reduce complexity to make the code more efficient
- Change for loop to while or loop
- Delete variable array,length, and replace length for size.

**Comment by HillaryOkello** [comment]
Thank you for pointing out the issues guys. We have fixed all of them.
